name: 'Tag Version'
description: 'Figure out version number from tags'
inputs:
  args:  # id of input
    description: 'tag-version arguments'
    required: true
    default: '-h'
  command:
    description: 'Section of the semantic version in the format v<major>.<minor>.<patch>'
    required: true
    default: 'minor'
outputs:
  version: # id of output
    description: 'Verion number'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.args }}