on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Version test
        id: version
        uses: actions/tag-version-action@v1
        with:
          args: '-firs'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.version.outputs.version }}"